#:schema https://raw.githubusercontent.com/cloudflare/wrangler2/sys-config-schema/packages/wrangler/config-schema.json
name = "restoration-reviews"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".next"

[build]
command = "npm run build"
